/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hnsn.kaukus.node;

import com.google.inject.Guice;
import com.google.inject.Inject;

import io.hnsn.kaukus.node.configuration.NodeConfiguration;
import io.hnsn.kaukus.node.guiceModules.NodeModule;

public class App {
    private NodeConfiguration _configuration;

    public static void main(String[] args) {
        var injector = Guice.createInjector(new NodeModule());
        var app = injector.getInstance(App.class);
        app.Start();
    }

    @Inject
    App(NodeConfiguration configuration) {
        _configuration = configuration;
    }

    private void Start() {
        
    }
}
