/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.hnsn.kaukus.java-library-conventions")
}

dependencies {
    // api(project(":list"))
    compileOnly("org.slf4j:slf4j-api:1.7.30")
}
