/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.hnsn.kaukus.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.typesafe:config:1.4.1")
    implementation(project(":utilities"))
    implementation("com.google.inject:guice:5.1.0")
}

application {
    // Define the main class for the application.
    mainClass.set("io.hnsn.kaukus.node.App")
}
